### PR TITLE
Added myself to the pair authors for the future

### PR DESCRIPTION
**Pull request by johnfig**
Thought this may be useful. Let me know if there is another way you would like me to add myself. Thanks!

### CODE REVIEW

**Comment by myokomu** [comment]
lol @johnfig

**Comment by johnfig** [comment]
Hahahaha, miss you Stevie! @myokomu

**Comment by drjacobs** [comment]
How are you guys doing this?

**Comment by myokomu** [comment]
I think it's a public repo

**Comment by drjacobs** [comment]
👍 🍏

**Comment by myokomu** [comment]
:shipit:

**Comment by tjian** [comment]
🎉

**Comment by rootedbox** [comment]
👯‍♂️

**Comment by tlands** [comment]
😛 sup y'all!

**Comment by johnfig** [comment]
I loved that closing this PR started this. It's been a while since we've had a Goodshop reunion. We should all get drinks soon!

**Comment by jamesyp** [comment]
I don't see any specs here. 👎

**Pull request closed without merging**
